# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-09 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_auto_20200103_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=30, verbose_name='账号')),
                ('productid', models.IntegerField(verbose_name='ID')),
                ('productnum', models.IntegerField(verbose_name='产品数量')),
                ('productprice', models.FloatField(max_length=10, verbose_name='产品价格')),
                ('isChose', models.BooleanField(default=True, verbose_name='是否选中')),
                ('productimg', models.CharField(max_length=30, verbose_name='产品图片')),
                ('productname', models.CharField(max_length=30, verbose_name='产品名称')),
                ('orderid', models.IntegerField(default=0, verbose_name='订单编号')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
        ),
        migrations.AlterModelOptions(
            name='foodtypes',
            options={'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': '商品表'},
        ),
        migrations.AlterModelOptions(
            name='mustbuy',
            options={'verbose_name_plural': '必买小轮播'},
        ),
        migrations.AlterModelOptions(
            name='nav',
            options={'verbose_name_plural': '类别导航'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterModelOptions(
            name='wheel',
            options={'verbose_name_plural': '轮播大图'},
        ),
        migrations.AlterField(
            model_name='user',
            name='userAccount',
            field=models.CharField(max_length=20, unique=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userAddress',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userImg',
            field=models.CharField(max_length=150, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPasswd',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=20, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userRank',
            field=models.IntegerField(verbose_name='等级'),
        ),
    ]
