# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_auto_20200109_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(verbose_name='订单ID')),
                ('userid', models.CharField(max_length=30, verbose_name='用户ID')),
                ('progress', models.CharField(max_length=100, verbose_name='订单进度')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '购物车'},
        ),
    ]
